services:
  backend:
    build:
      context: ./backend
    container_name: portfolio-backend
    ports:
      - "5001:5000"
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/portfolio?authSource=admin
      - PORT=5000
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - portfolio-nw
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - portfolio-nw
    restart: always

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - portfolio-nw
    restart: always
    healthcheck:
      test: ["CMD","mongosh","--eval","db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  networks:
    portfolio-nw:
      driver: bridge

volumes:
    mongo-data:



