all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/instance1-key
    ansible_python_interpreter: /usr/bin/python3

  children:
    portfolio_server:
      hosts:
        single-node:
          ansible_host: 13.233.114.19

    web_tier:
      hosts:
        single-node:

    data_tier:
      hosts:
        single-node:

