all:
  children:
    jenkins:
      hosts:
        jenkins-server:
          ansible_host: "{{ lookup('env', 'JENKINS_IP') }}"
          ansible_user: ubuntu
    k8s_master:
      hosts:
        master-node:
          ansible_host: "{{ lookup('env', 'MASTER_IP') }}"
          ansible_user: ubuntu
    k8s_workers:
      hosts:
        worker-node-1:
          ansible_host: "{{ lookup('env', 'WORKER1_IP') }}"
          ansible_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ~/.ssh/portfolio-key.pem
