apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-config
  namespace: portfolio
data:
  MONGO_DATABASE: "portfolio"
  NODE_ENV: "production"
  PORT: "5000"
  FRONTEND_URL: "http://13.234.115.135:31441"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_FROM: "shubhamsingh74888@gmail.com"
  CONTACT_RECEIVER_EMAIL: "shubhamsingh74888@gmail.com"
  SMTP_USER: "shubhamsingh74888@gmail.com"
