apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: portfolio
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "password"
  JWT_SECRET: "mysuper_secret_jwt_key_2026"
  SMTP_PASS: "wuzxcuqymsghmqmz"
