apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: portfolio
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "REPLACE_WITH_MONGO_PASSWORD"
  JWT_SECRET: "REPLACE_WITH_JWT_SECRET"
  SMTP_PASS: "REPLACE_WITH_GMAIL_APP_PASSWORD"
